inherit_from: .rubocop_todo.yml

require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - '**/tmp/**/*'
    - '**/vendor/**/*'
