inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
  - standard

inherit_gem:
  standard:
    - config/base.yml
    - config/ruby-2.5.yml
    - config/ruby-2.6.yml
    - config/ruby-2.7.yml
    - config/ruby-3.0.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - '**/tmp/**/*'
    - '**/vendor/**/*'

RSpec/FilePath:
  SpecSuffixOnly:
    true
