# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test only supported versions: https://endoflife.date/ruby
        ruby-version: [ '3.1', '3.2', '3.3', head, jruby, jruby-head, truffleruby, truffleruby-head ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Set up Appraisal
      run: bundle exec appraisal install

    - name: Run tests
      run: CC_TEST_REPORTER_ID=1 bundle exec appraisal rspec

    - name: Publish code coverage
      if: ${{ success() && env.CC_TEST_REPORTER_ID && matrix.ruby-version == '3.2' }}
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  rubocop:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Run rubocop
      run: bundle exec rubocop

  standardrb:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Run standardb
      run: bundle exec standardrb
